
import java.awt.GraphicsDevice;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import java.awt.AWTEvent.*;
import java.nio.file.Files;
import javax.crypto.Cipher;
import static javax.management.Query.gt;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import jdk.nashorn.internal.ir.BreakNode;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jadha
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    Login s = new Login();

    /**
     *
     */
    String uname = s.userName;
    String selectedfile, selectedfilelocation;
    public static File file;
    String filename, time;
    String fname;
    boolean sensitivedata;
    String fullname, email, mobileno, RegDate;

    public HomePage() {
        initComponents();
        jPanel2.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        UserFullNamejLabel1.setText(DbConnection.userditailse(s.userName));
        jFrame2.setExtendedState(MAXIMIZED_BOTH);
        uploadButton2.setVisible(false);

        massegeupload.setVisible(false);
        jPanel3.setVisible(false);
        // jTable1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewTextArea1 = new javax.swing.JTextArea();
        FileNameLabale = new javax.swing.JLabel();
        closejButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        uploadButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewjButton2 = new javax.swing.JButton();
        DeletejButton2 = new javax.swing.JButton();
        userjLabel1 = new javax.swing.JLabel();
        massegeupload = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ProNamejLabel8 = new javax.swing.JLabel();
        ProEmailjLabel9 = new javax.swing.JLabel();
        ProMobilejLabel10 = new javax.swing.JLabel();
        ProRegjLabel11 = new javax.swing.JLabel();
        UserFullNamejLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProfilejButton2 = new javax.swing.JButton();
        fileuploadjButton1 = new javax.swing.JButton();
        filereadjButton1 = new javax.swing.JButton();
        logoutjButton2 = new javax.swing.JButton();
        HomejButton3 = new javax.swing.JButton();

        jFrame2.setBackground(new java.awt.Color(204, 255, 204));
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewTextArea1.setColumns(20);
        viewTextArea1.setRows(5);
        jScrollPane2.setViewportView(viewTextArea1);

        jFrame2.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 639, 550));
        jFrame2.getContentPane().add(FileNameLabale, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 269, -1));

        closejButton1.setBackground(new java.awt.Color(0, 51, 153));
        closejButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        closejButton1.setForeground(new java.awt.Color(255, 255, 255));
        closejButton1.setText("Close");
        closejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closejButton1ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(closejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Handling Data Security");
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uploadButton2.setBackground(new java.awt.Color(153, 153, 255));
        uploadButton2.setText("Upload File");
        uploadButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(uploadButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 72, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("Select file you want to upload");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 12, 447, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setDoubleBuffered(false);
        jPanel2.setEnabled(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "File Name", "File Location", "Time Modified", "Date Modifide"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 2, 1210, 249));

        viewjButton2.setText("View");
        viewjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(viewjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 281, -1, -1));

        DeletejButton2.setText("Delete");
        DeletejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(DeletejButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 281, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 101, 1210, 650));
        jPanel1.add(userjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 66, 186, -1));
        jPanel1.add(massegeupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 72, 142, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email Id :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile No :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Reg Date :");

        ProNamejLabel8.setBackground(new java.awt.Color(0, 0, 102));
        ProNamejLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ProEmailjLabel9.setBackground(new java.awt.Color(0, 0, 102));
        ProEmailjLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ProMobilejLabel10.setBackground(new java.awt.Color(0, 0, 102));
        ProMobilejLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ProRegjLabel11.setBackground(new java.awt.Color(0, 0, 102));
        ProRegjLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(ProRegjLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ProMobilejLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(ProNamejLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProEmailjLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProNamejLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ProEmailjLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProMobilejLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ProRegjLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        UserFullNamejLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UserFullNamejLabel1.setForeground(new java.awt.Color(0, 51, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Welcome");

        ProfilejButton2.setBackground(new java.awt.Color(0, 51, 102));
        ProfilejButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ProfilejButton2.setForeground(new java.awt.Color(255, 255, 255));
        ProfilejButton2.setText("Profile");
        ProfilejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilejButton2ActionPerformed(evt);
            }
        });

        fileuploadjButton1.setBackground(new java.awt.Color(0, 51, 102));
        fileuploadjButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fileuploadjButton1.setForeground(new java.awt.Color(255, 255, 255));
        fileuploadjButton1.setText("FileUpload");
        fileuploadjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileuploadjButton1ActionPerformed(evt);
            }
        });

        filereadjButton1.setBackground(new java.awt.Color(0, 51, 102));
        filereadjButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        filereadjButton1.setForeground(new java.awt.Color(255, 255, 255));
        filereadjButton1.setText("FileRead");
        filereadjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filereadjButton1ActionPerformed(evt);
            }
        });

        logoutjButton2.setBackground(new java.awt.Color(0, 51, 102));
        logoutjButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logoutjButton2.setForeground(new java.awt.Color(255, 255, 255));
        logoutjButton2.setText("Logout");
        logoutjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButton2ActionPerformed(evt);
            }
        });

        HomejButton3.setBackground(new java.awt.Color(0, 51, 102));
        HomejButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HomejButton3.setForeground(new java.awt.Color(255, 255, 255));
        HomejButton3.setText("Home");
        HomejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomejButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileuploadjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(filereadjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfilejButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomejButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserFullNamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserFullNamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HomejButton3)
                .addGap(36, 36, 36)
                .addComponent(ProfilejButton2)
                .addGap(36, 36, 36)
                .addComponent(fileuploadjButton1)
                .addGap(36, 36, 36)
                .addComponent(filereadjButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutjButton2)
                .addGap(57, 57, 57))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void uploadButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButton2ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        uploadButton2.setVisible(true);

        massegeupload.setVisible(true);

        massegeupload.setText(".......");
        //System.out.println(uname);
        JFileChooser fileChooser = new JFileChooser("D:\\Encryption And Dicryption");
        fileChooser.showOpenDialog(null);
        file = fileChooser.getSelectedFile();
        File f = new File("D:\\Handling Data Security\\Encryptfiles\\" + file.getName());
        if (f.exists()) {
            JOptionPane.showMessageDialog(null, "change your file name");
        } else {
            System.out.println("file sensitive data cheking start.......");
            try {
                sensitivedata = SensitiveFile.sensitiveData(file);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (sensitivedata) {
                System.out.println("File uploading start.....");
                FileNameLabale.setText(file.getName());
                String q = "insert into fileoperation(UserName,FileName,uploadTime,Date,FileLocation) values('" + uname + "','" + file.getName() + "',curtime(),curdate(),'" + file.getAbsoluteFile() + "')";
                DbConnection con = new DbConnection();
                con.Qary(q);
                massegeupload.setText(file.getName() + " Upload success.");

                File f1 = new File("D:\\Handling Data Security\\Encryptfiles\\" + file.getName());
                try {
                    Files.copy(file.toPath(), f1.toPath());
                } catch (IOException ex) {
                    System.out.println("Error...." + ex);
                }
                Encryption.Encrypt(f1);

            } else {
                JOptionPane.showMessageDialog(null, "file Not sensitive");
            }
        }

    }//GEN-LAST:event_uploadButton2ActionPerformed

    private void fileuploadjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileuploadjButton1ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);

        massegeupload.setVisible(true);
        viewjButton2.setVisible(true);
        uploadButton2.setVisible(true);
        jPanel2.setVisible(false);
        jLabel2.setText("Select file you want to upload");
        // JTable table = new JTable();
    }//GEN-LAST:event_fileuploadjButton1ActionPerformed

    private void filereadjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filereadjButton1ActionPerformed
        // TODO add your handling code here:

        jPanel3.setVisible(false);
        massegeupload.setVisible(false);
        viewjButton2.setVisible(true);
        uploadButton2.setVisible(false);

        jPanel2.setVisible(true);
        jTable1.setVisible(true);
        DeletejButton2.setVisible(true);
        jLabel2.setText("You have uploaded following files");

        try {
            //1
            System.out.println("Driver Load Success");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasecurity", "root", "7764");//2
            Statement stmt = con.createStatement();
            PreparedStatement statement = con.prepareStatement("select *from fileoperation where UserName='" + s.userName + "'");
            ResultSet rs = statement.executeQuery();

            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("FileName"), rs.getString("FileLocation"), rs.getString("uploadTime"), rs.getString("Date")};
                tm.addRow(o);
            }

            con.close();//5
        } catch (SQLException e) {
            System.out.println("SQL Probelm : " + e);
        }
    }//GEN-LAST:event_filereadjButton1ActionPerformed

    private void logoutjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButton2ActionPerformed
        String[] args = null;
        super.dispose();
        Login.main(args);
    }//GEN-LAST:event_logoutjButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        System.out.println("Table file");
        jPanel3.setVisible(false);
        DefaultTableModel db = new DefaultTableModel();
        db = (DefaultTableModel) jTable1.getModel();
        filename = (String) db.getValueAt(jTable1.getSelectedRow(), 0);
        time = (String) db.getValueAt(jTable1.getSelectedRow(), 2);


    }//GEN-LAST:event_jTable1MouseClicked

    private void ProfilejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilejButton2ActionPerformed
        // TODO add your handling code here:
        jTable1.setVisible(false);
        // hidetable();
        jPanel2.setVisible(false);

        jPanel3.setVisible(true);
        jPanel3.setAlignmentY(java.awt.Component.CENTER_ALIGNMENT);
        ProNamejLabel8.setVisible(true);
        ProEmailjLabel9.setVisible(true);
        ProMobilejLabel10.setVisible(true);
        ProRegjLabel11.setVisible(true);
        //jPanel2.setVisible(true);

        jLabel2.setText("                                                             Profile");
        uploadButton2.setVisible(false);
        viewjButton2.setVisible(false);
        massegeupload.setVisible(false);

        try {
            //1
            System.out.println("Driver Load Success");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasecurity", "root", "7764");//2
            Statement stmt = con.createStatement();
            PreparedStatement statement = con.prepareStatement("select *from userdetails where email='" + s.userName + "'");
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                fullname = rs.getString("fullName");
                email = rs.getString("email");
                mobileno = rs.getString("mobileNo");
                RegDate = rs.getString("date");
                ProNamejLabel8.setText(fullname);
                ProEmailjLabel9.setText(email);
                ProMobilejLabel10.setText(mobileno);
                ProRegjLabel11.setText(RegDate);
                System.out.println(fullname);
            }

            con.close();//5
        } catch (SQLException e) {
            System.out.println("SQL Probelm : " + e);
        }
    }//GEN-LAST:event_ProfilejButton2ActionPerformed

    private void viewjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButton2ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRowCount() == 1) {
            jFrame2.setVisible(true);
            File dfile = new File("D:\\Handling Data Security\\Temp Dycrypt\\" + filename);
            File efile = new File("D:\\Handling Data Security\\Encryptfiles\\" + filename);

            try {
                Files.copy(efile.toPath(), dfile.toPath());
            } catch (IOException ex) {
                System.out.println("Error...." + ex);
            }
            System.out.println("dycryption start.....");
            String key = "Swapnilrerererer";
            File inputFile = new File("D:\\Handling Data Security\\Temp Dycrypt\\" + filename);

            try {

                EncryptDecrypt.fileProcessor(Cipher.DECRYPT_MODE, key, inputFile, inputFile);

                System.out.println("Sucess");
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
                ex.printStackTrace();
            }

            //System.out.println("HomePag==========>"+filename);
            System.out.println("file reading start");
            FileReader rd = null;
            try {
                rd = new FileReader("D:\\Handling Data Security\\Temp Dycrypt\\" + filename);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader br = new BufferedReader(rd);
            try {
                viewTextArea1.read(br, null);
                br.close();
                rd.close();
            } catch (IOException ex) {
                Logger.getLogger(filereadtest.class.getName()).log(Level.SEVERE, null, ex);
            }

            viewTextArea1.requestFocus();

        } else {
            JOptionPane.showMessageDialog(null, "Your Not Select file");
        }
    }//GEN-LAST:event_viewjButton2ActionPerformed

    private void closejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closejButton1ActionPerformed
        // TODO add your handling code here:

        jFrame2.dispose();
        viewTextArea1.selectAll();
        viewTextArea1.replaceSelection("");
        File delete = new File("D:\\Handling Data Security\\Temp Dycrypt\\" + filename);
        delete.delete();
    }//GEN-LAST:event_closejButton1ActionPerformed

    private void DeletejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButton2ActionPerformed
        // TODO add your handling code here:
        jFrame2.dispose();
        DefaultTableModel tmodel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {
            tmodel.removeRow(jTable1.getSelectedRow());
            String q = "delete from fileoperation where UserName='" + s.userName + "' and fileName='" + filename + "' and uploadTime='" + time + "'";
            DbConnection.Qary(q);
            File fDelete = new File("D:\\Handling Data Security\\Encryptfiles\\" + filename);
            fDelete.delete();

        } else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Tabele is empty.");

            } else {
                JOptionPane.showMessageDialog(this, "please select single row for delete.");

            }

        }
    }//GEN-LAST:event_DeletejButton2ActionPerformed

    private void HomejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomejButton3ActionPerformed
        // TODO add your handling code here:
        uploadButton2.setVisible(false);

        massegeupload.setVisible(false);
        jTable1.setVisible(false);
        viewjButton2.setVisible(false);
        DeletejButton2.setVisible(false);
        jPanel2.setVisible(false);
        jLabel2.setText("                                                                About");
        jPanel3.setVisible(false);
    }//GEN-LAST:event_HomejButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // HomePage.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //j.setUndecorated(true);
        //j.setSize(1000,1000);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new HomePage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletejButton2;
    private javax.swing.JLabel FileNameLabale;
    private javax.swing.JButton HomejButton3;
    private javax.swing.JLabel ProEmailjLabel9;
    private javax.swing.JLabel ProMobilejLabel10;
    private javax.swing.JLabel ProNamejLabel8;
    private javax.swing.JLabel ProRegjLabel11;
    private javax.swing.JButton ProfilejButton2;
    private javax.swing.JLabel UserFullNamejLabel1;
    private javax.swing.JButton closejButton1;
    private javax.swing.JButton filereadjButton1;
    private javax.swing.JButton fileuploadjButton1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutjButton2;
    private javax.swing.JLabel massegeupload;
    private javax.swing.JButton uploadButton2;
    private javax.swing.JLabel userjLabel1;
    private javax.swing.JTextArea viewTextArea1;
    private javax.swing.JButton viewjButton2;
    // End of variables declaration//GEN-END:variables
}
